import type { ExamCentre } from "./types";

export const seedCentres: ExamCentre[] = [
  {
    id: "patna-abc-public-school",
    name: "ABC Public School",
    address: "Near Boring Road, Patna, Bihar",
    district: "Patna",
    state: "Bihar",
    latitude: 25.6159,
    longitude: 85.1107,
    landmark: "Boring Road crossing",
    examType: "Government recruitment",
    gateInfo: "Main gate on the west side",
    adminNotes: "Seed data for MVP testing.",
    verifiedStatus: "verified",
    pois: [
      {
        id: "patna-junction",
        name: "Patna Junction",
        category: "railway_station",
        address: "Station Road, Patna",
        latitude: 25.6022,
        longitude: 85.1376,
        verifiedStatus: "verified",
        source: "manual",
        distanceMeters: 3200,
        walkingTimeMinutes: 39,
        drivingTimeMinutes: 12,
        priorityRank: 1,
      },
      {
        id: "jay-prakash-airport",
        name: "Jay Prakash Narayan Airport",
        category: "airport",
        address: "Shaheed Pir Ali Khan Marg, Patna",
        latitude: 25.5913,
        longitude: 85.0879,
        verifiedStatus: "verified",
        source: "manual",
        distanceMeters: 4700,
        walkingTimeMinutes: 58,
        drivingTimeMinutes: 18,
        priorityRank: 1,
      },
      {
        id: "boring-road-photocopy",
        name: "Boring Road Photocopy",
        category: "photocopy",
        address: "Boring Road, Patna",
        latitude: 25.6168,
        longitude: 85.1131,
        openingHours: "07:00-21:00",
        verifiedStatus: "unverified",
        source: "student",
        distanceMeters: 260,
        walkingTimeMinutes: 4,
        drivingTimeMinutes: 2,
        priorityRank: 1,
      },
      {
        id: "sbi-atm-boring-road",
        name: "SBI ATM",
        category: "atm",
        address: "Boring Road, Patna",
        latitude: 25.6148,
        longitude: 85.1122,
        verifiedStatus: "verified",
        source: "manual",
        distanceMeters: 210,
        walkingTimeMinutes: 3,
        drivingTimeMinutes: 1,
        priorityRank: 1,
      },
      {
        id: "boring-road-food-court",
        name: "Boring Road Food Court",
        category: "restaurant",
        address: "Boring Road, Patna",
        latitude: 25.6173,
        longitude: 85.1098,
        verifiedStatus: "unverified",
        source: "osm",
        distanceMeters: 190,
        walkingTimeMinutes: 3,
        drivingTimeMinutes: 1,
        priorityRank: 1,
      },
      {
        id: "nearby-medical-store",
        name: "Care Medical Store",
        category: "medical_store",
        address: "Sri Krishna Puri, Patna",
        latitude: 25.6146,
        longitude: 85.1076,
        verifiedStatus: "verified",
        source: "manual",
        distanceMeters: 340,
        walkingTimeMinutes: 5,
        drivingTimeMinutes: 2,
        priorityRank: 1,
      },
    ],
  },
  {
    id: "patna-ganga-exam-centre",
    name: "Ganga Exam Centre",
    address: "Kankarbagh Main Road, Patna, Bihar",
    district: "Patna",
    state: "Bihar",
    latitude: 25.5928,
    longitude: 85.1627,
    landmark: "Near old bypass",
    examType: "Entrance exam",
    verifiedStatus: "unverified",
    pois: [
      {
        id: "kankarbagh-bus-stop",
        name: "Kankarbagh Bus Stop",
        category: "bus_stop",
        address: "Kankarbagh Main Road, Patna",
        latitude: 25.5937,
        longitude: 85.1616,
        verifiedStatus: "unverified",
        source: "osm",
        distanceMeters: 150,
        walkingTimeMinutes: 2,
        drivingTimeMinutes: 1,
        priorityRank: 1,
      },
      {
        id: "kankarbagh-cyber-cafe",
        name: "Quick Net Cyber Cafe",
        category: "cyber_cafe",
        address: "Kankarbagh, Patna",
        latitude: 25.5919,
        longitude: 85.1644,
        verifiedStatus: "unverified",
        source: "student",
        distanceMeters: 220,
        walkingTimeMinutes: 4,
        drivingTimeMinutes: 2,
        priorityRank: 1,
      },
      {
        id: "kankarbagh-parking",
        name: "Public Parking",
        category: "parking",
        address: "Kankarbagh Main Road, Patna",
        latitude: 25.5941,
        longitude: 85.1638,
        verifiedStatus: "reported",
        source: "student",
        distanceMeters: 190,
        walkingTimeMinutes: 3,
        drivingTimeMinutes: 2,
        priorityRank: 2,
      },
    ],
  },
];
